services:
  zayka:
    image: itzcrazykns1337/vane:latest
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - data:/home/zayka/data
    restart: unless-stopped

volumes:
  data:
    name: 'zayka-data'
