FROM node:24.5.0-slim AS builder

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/zayka

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY drizzle ./drizzle

RUN mkdir -p /home/zayka/data
RUN yarn build

FROM node:24.5.0-slim

RUN apt-get update && apt-get install -y python3 python3-pip sqlite3 && rm -rf /var/lib/apt/lists/*

WORKDIR /home/zayka

COPY --from=builder /home/zayka/public ./public
COPY --from=builder /home/zayka/.next/static ./public/_next/static

COPY --from=builder /home/zayka/.next/standalone ./
COPY --from=builder /home/zayka/data ./data
COPY drizzle ./drizzle

RUN mkdir /home/zayka/uploads

RUN yarn add playwright
RUN yarn playwright install --with-deps --only-shell chromium

EXPOSE 3000

CMD ["node", "server.js"]
